# Generated by Django 6.1.1 on 2026-10-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JenisServis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_servis', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True)),
                ('estimasi_waktu', models.PositiveIntegerField(help_text='Estimasi waktu dalam menit')),
                ('harga', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
