# Generated by Django 6.1.1 on 2026-09-29 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kendaraan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_polisi', models.CharField(max_length=15, unique=True)),
                ('merk', models.CharField(max_length=50)),
                ('model_kendaraan', models.CharField(max_length=50)),
                ('tahun', models.PositiveIntegerField()),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_kendaraan', to='accounts.pelanggan')),
            ],
        ),
        migrations.CreateModel(
            name='Mobil',
            fields=[
                ('kendaraan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kendaraan.kendaraan')),
                ('jumlah_pintu', models.PositiveIntegerField()),
                ('jenis_mobil', models.CharField(max_length=30)),
            ],
            bases=('kendaraan.kendaraan',),
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('kendaraan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kendaraan.kendaraan')),
                ('jenis_motor', models.CharField(max_length=30)),
                ('kapasitas_mesin', models.PositiveIntegerField(help_text='dalam cc')),
            ],
            bases=('kendaraan.kendaraan',),
        ),
        migrations.CreateModel(
            name='Truk',
            fields=[
                ('kendaraan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kendaraan.kendaraan')),
                ('kapasitas_muatan_kg', models.PositiveIntegerField()),
                ('jumlah_sumbu', models.PositiveIntegerField(default=2)),
            ],
            bases=('kendaraan.kendaraan',),
        ),
    ]
