# Generated by Django 6.1.1 on 2026-10-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransaksiServis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_transaksi', models.CharField(max_length=50, unique=True, verbose_name='Kode Transaksi')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('total_biaya', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
    ]
