# Generated by Django 6.1.1 on 2026-10-08 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('kendaraan', '0001_initial'),
        ('mekanik', '0001_initial'),
        ('servis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksiservis',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaksiservis',
            name='keluhan',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='transaksiservis',
            name='kendaraan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kendaraan.kendaraan'),
        ),
        migrations.AddField(
            model_name='transaksiservis',
            name='konfirmasi_pelanggan',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaksiservis',
            name='lokasi_servis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaksiservis',
            name='mekanik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaksi_servis', to='accounts.mekanik'),
        ),
        migrations.AddField(
            model_name='transaksiservis',
            name='pelanggan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.pelanggan'),
        ),
        migrations.AddField(
            model_name='transaksiservis',
            name='rekomendasi_perbaikan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaksiservis',
            name='status',
            field=models.CharField(choices=[('MENUNGGU', 'Menunggu'), ('MENUNGGU_KONFIRMASI_MEKANIK', 'Menunggu Konfirmasi Mekanik'), ('MENUNGGU_KONFIRMASI', 'Menunggu Konfirmasi Pelanggan'), ('DIKERJAKAN', 'Dikerjakan'), ('SELESAI', 'Selesai'), ('DIBATALKAN', 'Dibatalkan')], default='MENUNGGU', max_length=30),
        ),
        migrations.AddField(
            model_name='transaksiservis',
            name='tipe_layanan',
            field=models.CharField(choices=[('DI_BENGKEL', 'Di Bengkel'), ('HOME_SERVICE', 'Home Service')], default='DI_BENGKEL', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaksiservis',
            name='kode_transaksi',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Kode Transaksi'),
        ),
        migrations.CreateModel(
            name='DetailServis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField(default=1)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('jenis_servis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detail_transaksi', to='mekanik.jenisservis')),
                ('transaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_servis', to='servis.transaksiservis')),
            ],
        ),
    ]
