# Generated by Django 6.1.1 on 2026-10-07 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sparepart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True, verbose_name='Kode Sparepart')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Sparepart')),
                ('kategori', models.CharField(max_length=50, verbose_name='Kategori')),
                ('harga', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Harga (Rp)')),
                ('stok', models.IntegerField(default=0, verbose_name='Jumlah Stok')),
                ('stok_minimum', models.IntegerField(default=5, verbose_name='Stok Minimum')),
            ],
            options={
                'verbose_name': 'Sparepart',
                'verbose_name_plural': 'Data Sparepart',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='DetailSparepart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField(default=1, verbose_name='Jumlah')),
                ('harga_satuan', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Harga Satuan')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal')),
                ('transaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_sparepart', to='servis.transaksiservis', verbose_name='Transaksi Servis')),
                ('sparepart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detail_transaksi', to='sparepart.sparepart', verbose_name='Sparepart')),
            ],
            options={
                'verbose_name': 'Detail Sparepart',
                'verbose_name_plural': 'Detail Sparepart Transaksi',
            },
        ),
    ]
